name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=24.11.3=py312h7900ff3_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hd9148b4_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - distro=1.9.0=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.6.4=h5888daf_0
  - fmt=11.0.2=h434a139_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py312h8a5da7c_0
  - freetype=2.13.3=ha770c72_1
  - frozendict=2.4.6=py312h66e93f0_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=10.4.0=h76408a6_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.9=py312h0a2e395_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=h4585015_3
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp19.1=19.1.7=default_hb5137d0_3
  - libclang13=19.1.7=default_h9c6a7e4_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.6.3=hb9d3cd8_1
  - libmamba=1.5.12=h49b8a8d_0
  - libmambapy=1.5.12=py312hbaee817_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_0
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.48.0=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=1.5.12=py312h9460a1c_0
  - matplotlib=3.10.5=py312h7900ff3_0
  - matplotlib-base=3.10.5=py312he3d6523_0
  - menuinst=2.2.0=py312h7900ff3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.5=h2d0b736_2
  - numpy=2.3.2=py312hf476fde_1
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - pcre2=10.44=hc749103_2
  - pillow=11.3.0=py312h80c1187_0
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h66e93f0_2
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.8.2=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.8=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=5_cp312
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.2=h588cce1_0
  - readline=8.2=h8228510_1
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - ruamel.yaml=0.18.10=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.5.2=py312h4c3975b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.0=pyhd8ed1ab_0
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml-cpp=0.8.0=h59595ed_0
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /apps/common/software/Miniforge3/24.11.3-0
